POST http://localhost:3001/auth
Content-Type: application/json

{
    "name": "Eduard",
    "password": "Test1234"
}

################################
#

POST http://localhost:3001/auth
Content-Type: application/json

{
    "name": "Eduard",
    "password": "fkshbjdkafjdksghvbh"
}
