###
# Get all products
GET https://nodejs-esgi-server.herokuapp.com/products

###
# Get all products SARAH
GET https://product-esgi.herokuapp.com/products

###
# Get pizza product
GET https://node-esgi-cli.herokuapp.com/products/pizza


###
# Add new product
POST https://nodejs-esgi-server.herokuapp.com/products/add
Content-Type: application/json

{
    "name": "h Uh UH",
    "quantity": 2
}

###
# Delete 1 product
DELETE https://node-esgi-cli.herokuapp.com/products/quentin


###
# Delete product quantity
DELETE https://node-esgi-cli.herokuapp.com/products/quentin?quantity=500